# Generated by Django 4.0.1 on 2022-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Toiletries', 'Toiletries'), ('Stationary', 'Stationary'), ('Electronics', 'Electronics'), ('Food', 'Food'), ('Household', 'Household')], max_length=50, null=True),
        ),
    ]
